@startuml
actor User
participant AppWindowController << View >>
participant AppViewController << View >>
participant ContributionView << View Model >>
participant Contribution << Model >>

User -> AppWindowController: start app
AppWindowController -> AppViewController: instantiate/display
AppViewController -> ContributionView: instantiate
ContributionView -> Contribution: instantiate
ContributionView -> GitHubHelper: request data
GitHubHelper -> ContributionView: fill model
ContributionView -> AppViewController: update
User -> AppWindowController: quit app
AppWindowController -> User: quit app
@enduml