@startuml
actor User
participant AppWindowController << View >>
participant AppViewController << View >>
participant UsernameViewController << View Model >>
participant ContributionViewController << View Model >>
participant Contribution << Model >>
participant GitHubHelper << Helper >>

User -> AppWindowController: start app
AppWindowController -> AppViewController: instantiate
AppViewController -> UsernameViewController: instantiate
UsernameViewController -> AppViewController: display?
AppViewController -> ContributionViewController: instantiate with parameters
ContributionViewController -> GitHubHelper: request data
GitHubHelper -> ContributionViewController: send contribution data
ContributionViewController -> Contribution: instantiate with data
ContributionViewController -> ContributionViewController: fill model with contributions
ContributionViewController -> AppViewController: update
AppViewController -> AppWindowController: update
AppWindowController -> User: display
User -> AppWindowController: quit app
AppWindowController -> User: quit app
@enduml