# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'GitHub Contributions' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub Contributions
  pod 'Kanna', '~> 4.0.3'
  pod 'SwiftSVG', '~> 2.0'
end

target 'GitHub Contributions Widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHub Contributions Widget
  pod 'Kanna', '~> 4.0.3'
  pod 'SwiftSVG', '~> 2.0'
end
