# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'GitHub-Contributions-macOS' do
  use_frameworks!

  pod 'Kanna', '~> 4.0.3'
  pod 'SwiftSVG', '~> 2.0'
end
